### ISSUE TITLE
Mass update

### ISSUE THREAD

**Issue by kfir91** [Roche/ROGeTMF#3]
Hello,
Do you know about option to execute D2 mass update from third party application?

tnx

**Comment by troutguy** [comment]
There is this part of the API for D2FS.  I got this from D2FS SDK Javadoc from OT site (v 16.4).

com.emc.d2fs.models.massupdateinformations
Class MassUpdateInformations
java.lang.Object
com.emc.d2fs.models.massupdateinformations.MassUpdateInformations

Since a mass update is just an update query (?) couldn't a person right a DFC Java class that connects, runs IDfQuery interface and updates the proper objects? Just an idea...and this would be "third party".
